# Generated by Django 4.2 on 2025-05-14 15:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
