# Generated by Django 4.2 on 2025-05-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_tag_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
